openapi: 3.1.0

info:
  title: Saas Bootstrap API
  description: Description of the API.
  version: 1.0.0
servers:
  - url: https://localhost:8080/v1
    description: Local server.
paths:
  /auth/login:
    description: Login to the application.
    post:
      summary: Login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
            description: Bad Request
        '401':
            description: Unauthorized
        '500':
            description: Internal Server Error
      security: [ ]  # No security needed for login
components:
    schemas:
        LoginRequest:
          type: object
          properties:
            username:
              type: integer
              format: email
            password:
              type: string
              format: password
          required:
              - email
              - password
        LoginResponse:
          type: object
          properties:
            jwt:
              type: string
          required:
              - jwt
    securitySchemes:
      BasicAuth:
        type: http
        scheme: basic
